-- 1) 실험용 warehouse 
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;

-- 2) 실험용 DB/스키마
CREATE OR REPLACE DATABASE OBS_EXP_DB;
CREATE OR REPLACE SCHEMA OBS_EXP_DB.PUBLIC;

USE DATABASE OBS_EXP_DB;
USE SCHEMA PUBLIC;

-- 3) 메트릭 테이블 (간단형: 숫자 + 라벨)
CREATE OR REPLACE TABLE METRICS_INSERT (
  window_start TIMESTAMP_NTZ,
  window_end   TIMESTAMP_NTZ,
  source       STRING,
  metric_name  STRING,
  value        DOUBLE,
  labels       VARIANT
);

CREATE OR REPLACE TABLE METRICS_COPY LIKE METRICS_INSERT;

-- 4) 로그 테이블 (JSON lines를 VARIANT로 적재)
CREATE OR REPLACE TABLE LOGS_INSERT (
  window_start TIMESTAMP_NTZ,
  window_end   TIMESTAMP_NTZ,
  source       STRING,
  service      STRING,
  level        STRING,
  message      STRING,
  payload      VARIANT
);

CREATE OR REPLACE TABLE LOGS_COPY LIKE LOGS_INSERT;

-- 5) 내부 스테이지 + 파일포맷 (S3 없이도 실험 가능)
CREATE OR REPLACE STAGE OBS_EXP_STAGE;

CREATE OR REPLACE FILE FORMAT FF_METRICS_CSV
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE FILE FORMAT FF_LOGS_JSON
  TYPE = JSON;